displayName=Skilling Pet Odds Tracker
author=oneaaa
description=Tracks probability of receiving skilling pets (indev)
tags=pet,dry,skilling
version=
plugins=com.skillpetodds.SkillPetOddsPlugin
build=standard